### ISSUE TITLE
Plugin shouldn't write progress to stdout

### ISSUE THREAD

**Issue by larsmoil** [nodkz/babel-plugin-transform-relay-hot#2]
Hi
I notice this plugin writes `[transform-relay-hot] GraphQL Schema loaded successfully from...` to stdout. Progress should be written to stderr instead, as this output will pollute the JSON output when profiling otherwise: `webpack --profile --json >stats.json`. The offending code is at: https://github.com/nodkz/babel-plugin-transform-relay-hot/blob/master/index.js#L48

**Comment by nodkz** [comment]
Thanks, nice catch. Will fix it on this week.

Needs to add `verbose` option with false by default. And in `readme.md` add this option with `true` value. 

Will be awesome if you create PR. Otherwise I do it myself ASAP.
