### ISSUE TITLE
Support schema.graphql

### ISSUE THREAD

**Issue by maikelrobier** [nodkz/babel-plugin-transform-relay-hot#7]
Does the plugin support (or is planning to) schema files in `.graphql` format ?
I'm desperately looking for a plugin to hot reload the schema but I'm not sure if any of the existing ones currently support schema definitions generated with `printSchema()`:
```
    ["relay", {
      "compat": true,
      "schema": "./schema.graphql",
      }
    ]
```

**Comment by nodkz** [comment]
@maikelrobier sorry for late response.

Please try new version `1.0.2` I relaxed checking of schema file and update dependencies. So I suppose it should work out of the box. 

Let me know if it works or not for you.

**Comment by maikelrobier** [comment]
@nodkz `1.0.2` worked for me! Thanks!
